#!/usr/bin/env node
/**
 * UI/UX Optimize — Token Sync Tool.
 *
 * Generates src/lib/design-system.tsx from docs/design/design-tokens.json.
 * This ensures the code is always a faithful representation of the frozen tokens.
 */

const fs = require('fs');
const path = require('path');

const designTokensPath = path.join(process.cwd(), 'docs', 'design', 'design-tokens.json');
const outputDir = path.join(process.cwd(), 'src', 'lib');
const outputPath = path.join(outputDir, 'design-system.tsx');

if (!fs.existsSync(designTokensPath)) {
  console.error(`Error: ${designTokensPath} not found.`);
  process.exit(1);
}

try {
  const tokens = JSON.parse(fs.readFileSync(designTokensPath, 'utf8'));

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const tsxContent = `/**
 * AUTO-GENERATED DESIGN SYSTEM
 * Source: docs/design/design-tokens.json
 *
 * Do not edit this file directly. Update the source JSON and run the sync script.
 */

export const TOKENS = ${JSON.stringify(tokens, null, 2)} as const;

export type DesignTokens = typeof TOKENS;
`;

  fs.writeFileSync(outputPath, tsxContent);
  console.log(`✅ Successfully synced tokens to ${outputPath}`);
} catch (e) {
  console.error(`Error syncing tokens: ${e.message}`);
  process.exit(1);
}
