#!/usr/bin/env bash
# Full quality gate with auto-detection for multiple languages.
# Exit 0 = silent success, Exit 2 = errors surfaced to agent.
# Used in pre-commit hook and CI.
# NOTE: errexit disabled explicitly - it causes unpredictable failures in CI
# Why +e instead of -e? We need to capture command output before exiting,
# and we aggregate all failures before deciding the final exit code.
set +e
set -uo pipefail

# --- Configuration ---
# Use named constants for common exclusions
readonly GIT_EXCLUDE="./.git/*"

# --- Configuration ---
# Use named constants for common exclusions


REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

# Source lint-cache library
# shellcheck source=scripts/lib/lint_cache.sh
if [[ -f "$REPO_ROOT/scripts/lib/lint_cache.sh" ]]; then
    # shellcheck source=scripts/lib/lint_cache.sh
    source "$REPO_ROOT/scripts/lib/lint_cache.sh"
fi

# Colors for output (disabled in CI via TTY check, or via FORCE_COLOR=0)
if [[ -t 1 ]] && [[ "${FORCE_COLOR:-}" != "0" ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    RED=''
    GREEN=''
    NC=''
    YELLOW=''
    BLUE=''
fi

# FAILED acts as an error accumulator - any failed check sets this to 1
FAILED=0

# DETECTED_LANGUAGES stores which language ecosystems are present in the repo
DETECTED_LANGUAGES=()

readonly GITHUB_EVENT_PR='pull_request'

# Determine the current context
GITHUB_EVENT="${GITHUB_EVENT:-${GITHUB_EVENT_NAME:-}}"
GITHUB_REF="${GITHUB_REF:-}"

# Check if we're on main branch
ON_MAIN_BRANCH=false
if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/master" ]]; then
    ON_MAIN_BRANCH=true
fi

# Track if drift was detected
DRIFT_DETECTED=false

printf "Running quality gate...\n"
printf "\n"

# --- Validate git hooks configuration (prevent global hooks from overriding local) ---
if [[ "${SKIP_GLOBAL_HOOKS_CHECK:-false}" != "true" ]]; then
    printf "%bValidating git hooks configuration...%b\n" "${BLUE}" "${NC}"
    if ! ./scripts/validate-git-hooks.sh; then
        FAILED=1
    fi
    printf "\n"
fi

# --- LLM Context files check ---
printf "%bChecking LLM context files...%b\n" "${BLUE}" "${NC}"
if [[ ! -f "llms.txt" ]] || [[ ! -f "llms-full.txt" ]]; then
    if [[ "$GITHUB_EVENT" == "$GITHUB_EVENT_PR" ]]; then
        printf "%b  ⚠ llms.txt or llms-full.txt missing (auto-generated on main by workflow)%b\n" "${YELLOW}" "${NC}"
        DRIFT_DETECTED=true
    elif [[ "$ON_MAIN_BRANCH" == "true" ]]; then
        printf "%b  ⚠ llms.txt or llms-full.txt missing (gitignored, auto-generated by workflow)%b\n" "${YELLOW}" "${NC}"
    else
        printf "%b  ⚠ llms.txt or llms-full.txt not present (gitignored, generated by CI workflow)%b\n" "${YELLOW}" "${NC}"
    fi
else
    TMP_LLMS=$(mktemp)
    TMP_LLMS_FULL=$(mktemp)

    cleanup() {
        rm -f -- "$TMP_LLMS" "$TMP_LLMS_FULL"
        return 0
    }
    trap cleanup EXIT

    (
        export LLMS_TXT="$TMP_LLMS"
        export LLMS_FULL_TXT="$TMP_LLMS_FULL"
        if ! ./scripts/generate-llms-txt.sh > /dev/null 2>&1; then
            printf "%b  ✗ Failed to generate LLM context files%b\n" "${RED}" "${NC}"
            exit 1
        fi
    )

    llms_ok=true
    if ! diff -q llms.txt "$TMP_LLMS" > /dev/null; then
        if [[ "$GITHUB_EVENT" == "$GITHUB_EVENT_PR" ]]; then
            printf "%b  ⚠ llms.txt is out of date (auto-fixed on main by workflow)%b\n" "${YELLOW}" "${NC}"
        else
            printf "%b  ✗ llms.txt is out of date. Run ./scripts/generate-llms-txt.sh%b\n" "${RED}" "${NC}"
            FAILED=1
        fi
        DRIFT_DETECTED=true
        llms_ok=false
    fi

    if ! diff -q llms-full.txt "$TMP_LLMS_FULL" > /dev/null; then
        if [[ "$GITHUB_EVENT" == "$GITHUB_EVENT_PR" ]]; then
            printf "%b  ⚠ llms-full.txt is out of date (auto-fixed on main by workflow)%b\n" "${YELLOW}" "${NC}"
        else
            printf "%b  ✗ llms-full.txt is out of date. Run ./scripts/generate-llms-txt.sh%b\n" "${RED}" "${NC}"
            FAILED=1
        fi
        DRIFT_DETECTED=true
        llms_ok=false
    fi

    if $llms_ok; then
        printf "%b  ✓ llms.txt and llms-full.txt are up to date%b\n" "${GREEN}" "${NC}"
    fi
fi
printf "\n"

# --- Validate GitHub Actions SHAs ---
printf "%bValidating GitHub Actions SHAs...%b\n" "${BLUE}" "${NC}"
if ! ./scripts/validate-github-actions-shas.sh; then
    FAILED=1
fi
printf "\n"

# --- Validate Gemini TOML commands ---
if [[ -d ".gemini/commands" ]]; then
    printf "%bValidating Gemini TOML commands...%b\n" "${BLUE}" "${NC}"
    if ! python3 ./scripts/validate_gemini_toml.py; then
        FAILED=1
    fi
    printf "\n"
fi

# --- Validate GitHub Actions Workflows ---
printf "%bValidating GitHub Actions Workflows...%b\n" "${BLUE}" "${NC}"
if ! ./scripts/validate-workflows.sh; then
    FAILED=1
fi
printf "\n"

# --- Validate skills (symlinks and format) ---
printf "%bValidating skills...%b\n" "${BLUE}" "${NC}"
if ! ./scripts/validate-skills.sh; then
    FAILED=1
fi
printf "\n"

# --- Validate skills-reference.md drift ---
printf "%bChecking skills-reference.md is up to date...%b\n" "${BLUE}" "${NC}"
if [[ -f "agents-docs/skills-reference.md" ]]; then
    check_tmp=$(mktemp)
    if ! ./scripts/generate-skills-reference.sh --check > "$check_tmp" 2>&1; then
        if [[ "$GITHUB_EVENT" == "$GITHUB_EVENT_PR" ]]; then
            printf "%b  ⚠ skills-reference.md is out of date (auto-fix on main by workflow)%b\n" "${YELLOW}" "${NC}"
            DRIFT_DETECTED=true
        else
            printf "%b  ✗ skills-reference.md is out of date. Diff:%b\n" "${RED}" "${NC}"
            cat "$check_tmp" >&2
            FAILED=1
        fi
        rm -f "$check_tmp"
    else
        rm -f "$check_tmp"
        printf "%b  ✓ skills-reference.md is up to date%b\n" "${GREEN}" "${NC}"
    fi
else
    printf "%b  ⚠ agents-docs/skills-reference.md not present (regenerate with ./scripts/generate-skills-reference.sh)%b\n" "${YELLOW}" "${NC}"
fi
printf "\n"

# --- Validate reference links in SKILL.md files ---
printf "%bValidating reference links in SKILL.md files...%b\n" "${BLUE}" "${NC}"
if ! ./scripts/validate-links.sh; then
    FAILED=1
fi
printf "\n"

# --- ADR compliance check ---
if [[ -f "./scripts/check-adr-compliance.sh" ]]; then
    printf "%bChecking ADR compliance...%b\n" "${BLUE}" "${NC}"
    if ! ./scripts/check-adr-compliance.sh; then
        FAILED=1
    fi
    printf "\n"
fi

# --- Plan numbering check ---
if [[ -f "./scripts/check-plan-numbering.sh" ]]; then
    printf "%bChecking plan numbering...%b\n" "${BLUE}" "${NC}"
    if ! ./scripts/check-plan-numbering.sh; then
        FAILED=1
    fi
    printf "\n"
fi

# --- Validate .agents/metrics.jsonl ---
if [[ -f ".agents/metrics.jsonl" ]]; then
    printf "%bValidating .agents/metrics.jsonl...%b\n" "${BLUE}" "${NC}"
    METRICS_VALID=0

    # 1. First, check if the file is valid JSONL format
    # The jq empty filter "." checks parsing; redirecting output to /dev/null ensures it runs fast.
    if ! jq -c . .agents/metrics.jsonl >/dev/null 2>&1; then
        printf "%b  ✗ Invalid JSON in metrics.jsonl%b\n" "${RED}" "${NC}"
        METRICS_VALID=1
    fi

    # 2. If JSON is valid, check timestamps using jq which is much faster than grep
    if [[ $METRICS_VALID -eq 0 ]]; then
        # This will extract records where timestamp is missing or doesn't match the pattern.
        # If the output is empty, all timestamps are valid.
        bad_ts=$(jq -r 'select((.timestamp == null) or (.timestamp | type != "string") or (.timestamp | test("^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$") | not)) | (.timestamp | if . == "" then "empty" else . end // "missing")' .agents/metrics.jsonl 2>/dev/null || echo "jq-error")

        if [[ "$bad_ts" == "jq-error" ]]; then
            printf "%b  ✗ Failed to parse timestamps in metrics.jsonl%b\n" "${RED}" "${NC}"
            METRICS_VALID=1
        elif [[ -n "$bad_ts" ]]; then
            # Extract first bad timestamp for error message
            first_bad_ts=$(printf "%s\n" "$bad_ts" | head -n 1)
            printf "%b  ✗ Bad timestamp format \"%s\" in metrics.jsonl — must be YYYY-MM-DDTHH:MM:SSZ%b\n" "${RED}" "$first_bad_ts" "${NC}"
            METRICS_VALID=1
        fi
    fi

    if [[ $METRICS_VALID -eq 0 ]]; then
        printf "%b  ✓ .agents/metrics.jsonl is valid%b\n" "${GREEN}" "${NC}"
    else
        FAILED=1
    fi
    printf "\n"
fi

# --- Validate commitlint configuration consistency ---
if [[ -f "./tests/test-commitlint-rules.sh" ]]; then
    printf "%bValidating commitlint configuration...%b\n" "${BLUE}" "${NC}"
    if ! bash ./tests/test-commitlint-rules.sh; then
        FAILED=1
    fi
    printf "\n"
fi

# --- Enforce LOC limits ---
printf "%bEnforcing LOC limits...%b\n" "${BLUE}" "${NC}"
if ! ./scripts/loc_gate.sh; then
    FAILED=1
fi
printf "\n"

# --- Enforce WASM size limits ---
printf "%bEnforcing WASM size limits...%b\n" "${BLUE}" "${NC}"
if ! ./scripts/wasm_size_gate.sh; then
    FAILED=1
fi
printf "\n"

# --- Auto-detect project languages ---
printf "%bDetecting project languages...%b\n" "${BLUE}" "${NC}"

# Rust detection
if [[ -f "Cargo.toml" ]]; then
    printf "  %b✓%b Rust (Cargo.toml)\n" "${GREEN}" "${NC}"
    DETECTED_LANGUAGES+=("rust")
fi

# TypeScript/JavaScript detection
if [[ -f "package.json" ]]; then
    printf "  %b✓%b TypeScript/JavaScript (package.json)\n" "${GREEN}" "${NC}"
    DETECTED_LANGUAGES+=("typescript")
fi

# Python detection
if [[ -f "requirements.txt" ]] || [[ -f "pyproject.toml" ]] || [[ -f "setup.py" ]]; then
    printf "  %b✓%b Python (requirements.txt/pyproject.toml)\n" "${GREEN}" "${NC}"
    DETECTED_LANGUAGES+=("python")
fi

# Go detection
if [[ -f "go.mod" ]]; then
    printf "  %b✓%b Go (go.mod)\n" "${GREEN}" "${NC}"
    DETECTED_LANGUAGES+=("go")
fi

# Shell script detection
if find . -name "*.sh" -not -path "$GIT_EXCLUDE" -print -quit | grep -q .; then
    printf "  %b✓%b Shell scripts detected\n" "${GREEN}" "${NC}"
    DETECTED_LANGUAGES+=("shell")
fi

# Markdown detection
if find . -name "*.md" -not -path "$GIT_EXCLUDE" -print -quit | grep -q .; then
    printf "  %b✓%b Markdown files detected\n" "${GREEN}" "${NC}"
    DETECTED_LANGUAGES+=("markdown")
fi

if [[ ${#DETECTED_LANGUAGES[@]} -eq 0 ]]; then
    printf "%b  No recognized project files found.%b\n" "${YELLOW}" "${NC}"
fi
printf "\n"

# --- Get changed files for scoped linting ---
_changed_files_z() {
    local source_files=""

    # In CI PR context, compare against base branch
    if [[ -n "${GITHUB_BASE_REF:-}" ]]; then
        source_files=$(git diff --name-only "origin/${GITHUB_BASE_REF}...HEAD" 2>/dev/null || true)
    fi

    # Fallback: staged + unstaged changes vs HEAD
    if [[ -z "$source_files" ]]; then
        source_files=$(git diff --name-only HEAD 2>/dev/null || true)
    fi

    # If nothing changed (or first commit), fall back to all tracked files
    if [[ -z "$source_files" ]]; then
        source_files=$(git ls-files 2>/dev/null || true)
    fi

    # If still empty (no git), fall back to find
    if [[ -z "$source_files" ]]; then
        find . -type f -not -path "./.git/*" -not -path "./target/*" -not -path "*/node_modules/*" -print0 2>/dev/null || true
        return
    fi

    # Convert newline-delimited to null-delimited
    local IFS=$'\n'
    # shellcheck disable=SC2046
    printf '%s\0' $source_files
}

# --- Run language-specific checks ---

# Rust checks
if [[ " ${DETECTED_LANGUAGES[*]} " =~ " rust " ]]; then
    printf "%bRunning Rust checks...%b\n" "${BLUE}" "${NC}"
    if command -v cargo &> /dev/null; then
        if ! OUTPUT=$(cargo fmt --check 2>&1); then
            printf "%b  ✗ cargo fmt failed%b\n" "${RED}" "${NC}"
            printf "%s\n" "$OUTPUT" >&2
            FAILED=1
        else
            printf "%b  ✓ cargo fmt passed%b\n" "${GREEN}" "${NC}"
        fi
        if [[ "${SKIP_CLIPPY:-false}" != "true" ]]; then
            if ! OUTPUT=$(cargo clippy --all-targets -- -D warnings 2>&1); then
                printf "%b  ✗ cargo clippy failed%b\n" "${RED}" "${NC}"
                printf "%s\n" "$OUTPUT" >&2
                FAILED=1
            else
                printf "%b  ✓ cargo clippy passed%b\n" "${GREEN}" "${NC}"
            fi
        fi
        if [[ "${SKIP_TESTS:-false}" != "true" ]]; then
            if ! OUTPUT=$(cargo test --lib 2>&1); then
                printf "%b  ✗ cargo test failed%b\n" "${RED}" "${NC}"
                printf "%s\n" "$OUTPUT" >&2
                FAILED=1
            else
                printf "%b  ✓ cargo test passed%b\n" "${GREEN}" "${NC}"
            fi
        fi
    fi
    printf "\n"
fi

# TypeScript / JavaScript checks
if [[ " ${DETECTED_LANGUAGES[*]} " =~ " typescript " ]]; then
    printf "%bRunning TypeScript/JavaScript checks...%b\n" "${BLUE}" "${NC}"
    if command -v pnpm &> /dev/null; then
        if ! OUTPUT=$(pnpm lint 2>&1); then
            printf "%b  ✗ pnpm lint failed%b\n" "${RED}" "${NC}"
            printf "%s\n" "$OUTPUT" >&2
            FAILED=1
        else
            printf "%b  ✓ pnpm lint passed%b\n" "${GREEN}" "${NC}"
        fi
        if ! OUTPUT=$(pnpm typecheck 2>&1); then
            printf "%b  ✗ pnpm typecheck failed%b\n" "${RED}" "${NC}"
            printf "%s\n" "$OUTPUT" >&2
            FAILED=1
        else
            printf "%b  ✓ pnpm typecheck passed%b\n" "${GREEN}" "${NC}"
        fi
        if [[ "${SKIP_TESTS:-false}" != "true" ]]; then
            if ! OUTPUT=$(pnpm test 2>&1); then
                printf "%b  ✗ pnpm test failed%b\n" "${RED}" "${NC}"
                printf "%s\n" "$OUTPUT" >&2
                FAILED=1
            else
                printf "%b  ✓ pnpm test passed%b\n" "${GREEN}" "${NC}"
            fi
        fi
    fi
    printf "\n"
fi

# Shell script checks
if [[ " ${DETECTED_LANGUAGES[*]} " =~ " shell " ]]; then
    printf "%bRunning Shell script checks...%b\n" "${BLUE}" "${NC}"
    if command -v shellcheck &> /dev/null; then
        TMP_SH_LIST=$(mktemp)
        _changed_files_z | grep -z '\.sh$' > "$TMP_SH_LIST" 2>/dev/null || true
        if [[ -s "$TMP_SH_LIST" ]]; then
            # Do not pass -f quiet so errors are visible in CI
            if ! lint_batch_if_changed "$TMP_SH_LIST" "shellcheck" ".shellcheckrc" shellcheck --severity=error; then
                printf "%b  ✗ shellcheck failed%b\n" "${RED}" "${NC}"
                FAILED=1
            else
                printf "%b  ✓ shellcheck passed%b\n" "${GREEN}" "${NC}"
            fi
        else
            printf "%b  ✓ No changed shell files to check%b\n" "${GREEN}" "${NC}"
        fi
        rm -f -- "$TMP_SH_LIST"
    fi
    printf "\n"
fi

# Markdown checks
if [[ " ${DETECTED_LANGUAGES[*]} " =~ " markdown " ]]; then
    printf "%bRunning Markdown checks...%b\n" "${BLUE}" "${NC}"
    if command -v markdownlint-cli2 &> /dev/null; then
        TMP_MD_LIST=$(mktemp)
        _changed_files_z | grep -z '\.md$' > "$TMP_MD_LIST" 2>/dev/null || true
        if [[ -s "$TMP_MD_LIST" ]]; then
            if ! lint_batch_if_changed "$TMP_MD_LIST" "markdownlint" ".markdownlint-cli2.jsonc" markdownlint-cli2 >/dev/null 2>&1; then
                printf "%b  ✗ markdownlint-cli2 failed (run 'markdownlint-cli2 "**/*.md"' locally to see details)%b\n" "${RED}" "${NC}"
                FAILED=1
            else
                printf "%b  ✓ markdownlint-cli2 passed%b\n" "${GREEN}" "${NC}"
            fi
        else
            printf "%b  ✓ No changed markdown files to check%b\n" "${GREEN}" "${NC}"
        fi
        rm -f -- "$TMP_MD_LIST"
    fi
    printf "\n"
fi

# Special handling for drift detection based on context
if [[ "$DRIFT_DETECTED" == "true" ]]; then
    if [[ "$GITHUB_EVENT" == "$GITHUB_EVENT_PR" ]]; then
        # During pull_request, print warning but exit 0
        printf "%b─────────────────────────────────────────────────────────────────%b\n" "${YELLOW}" "${NC}"
        printf "%b│ ⚠ Quality Gate: Drift detected (warning only during PR)     │%b\n" "${YELLOW}" "${NC}"
        printf "%b─────────────────────────────────────────────────────────────────%b\n" "${YELLOW}" "${NC}"
        printf "\n"
        printf "Languages checked: %s\n" "${DETECTED_LANGUAGES[*]}"
        exit 0
    elif [[ "$ON_MAIN_BRANCH" == "true" ]]; then
        # On main branch, exit with 1
        printf "%b─────────────────────────────────────────────────────────────────%b\n" "${RED}" "${NC}"
        printf "%b│ ✗ Quality Gate FAILED (drift on main branch)                │%b\n" "${RED}" "${NC}"
        printf "%b─────────────────────────────────────────────────────────────────%b\n" "${RED}" "${NC}"
        printf "\n"
        printf "Languages checked: %s\n" "${DETECTED_LANGUAGES[*]}"
        exit 1
    fi
fi

# Final status
if [[ $FAILED -ne 0 ]]; then
    printf "%b─────────────────────────────────────────────────────────────────%b\n" "${RED}" "${NC}"
    printf "%b│ ✗ Quality Gate FAILED                                         │%b\n" "${RED}" "${NC}"
    printf "%b─────────────────────────────────────────────────────────────────%b\n" "${RED}" "${NC}"
    exit 2
fi

printf "%b─────────────────────────────────────────────────────────────────%b\n" "${GREEN}" "${NC}"
printf "%b│ ✓ All Quality Gates PASSED                                    │%b\n" "${GREEN}" "${NC}"
printf "%b─────────────────────────────────────────────────────────────────%b\n" "${GREEN}" "${NC}"
printf "\n"
printf "Languages checked: %s\n" "${DETECTED_LANGUAGES[*]}"
